### ISSUE TITLE
Module HTTPAlertHandler not working

### ISSUE THREAD

**Issue by martin-haller** [patron-it/opencanary#13]
The logging module HTTPAlertHandler looks like it is not working. In some previous versions it was running okay. 

It looks that the HTTP requests are not reaching the webserver. In webservers access log there are no requests from the honeypot.

When opencanary terminates, there are error messages "Deffered" in console (the same number as there are log messages which should be logged).

**Comment by webknjaz** [comment]
Oh, this sounds like they haven't been awaited properly or there's a chance that there are some network issues which prevent requests from being sent.

**Comment by webknjaz** [comment]
It looks like there are some logs on your web-page now. I've accidentally rewritten the config on your rpi so I cannot reverify it now.

Let's assume that the problem was related to https://github.com/patron-it/ansible-opencanary/issues/1 and https://github.com/patron-it/ansible-opencanary/issues/2 which should be addressed now.

P.S. Locally I couldn't reproduce the issue and when I tried to point the config on rpi to localhost (runing a simple `python3 -m http.server`) it received log queries.

**Comment by martin-haller** [comment]
I tried it with Ansible 2.7.5 and new roles but still the same problem. Later I have found, that the installation was missing "pyOpenSSL" library. Could you add it into the deps, please?

**Comment by webknjaz** [comment]
Actually, it should be there already as a transitive dependency of Twisted. I'm curious why your env is different. We'll need to investigate that more closely.
